!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        0121yT1T-Ashish_custom:
          path: dataset/0121yT1T-Ashish_custom
          prefix: ARnCino
          standardFeature: false
          versions:
            '1.0':
              modifiedDate: '2024-12-18 10:30:33'
        01mKmQ1B-User Interface:
          path: dataset/01mKmQ1B-User Interface
          prefix: ncino
          standardFeature: true
          versions:
            Fall 2023 Rel - v1:
              modifiedDate: '2024-12-18 10:44:08'
        0121yT1T-Ramya-custom:
          path: dataset/0121yT1T-Ramya-custom
          prefix: ARnCino
          standardFeature: false
          versions:
            '1.0':
              modifiedDate: '2024-12-18 18:29:56'
