!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        0121yT1T-Ashish_custom:
          path: dataset/0121yT1T-Ashish_custom
          prefix: ARnCino
          standardFeature: false
          versions:
            '1.0':
              modifiedDate: '2024-12-18 10:30:33'
