!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        0121yT1T-Ashish_custom:
          path: dataset/0121yT1T-Ashish_custom
          prefix: ARnCino
          standardFeature: false
          versions:
            '1.0':
              modifiedDate: '2024-12-18 10:30:33'
        01mKmQ1B-User Interface:
          path: dataset/01mKmQ1B-User Interface
          prefix: ncino
          standardFeature: true
          versions:
            Fall 2023 Rel - v1:
              modifiedDate: '2024-12-18 10:44:08'
        0121yT1T-Ramya-custom:
          path: dataset/0121yT1T-Ramya-custom
          prefix: ARnCino
          standardFeature: false
          versions:
            '1.0':
              modifiedDate: '2024-12-19 17:35:49'
        0121yT1T-ramya-temp3:
          path: dataset/0121yT1T-ramya-temp3
          prefix: ARnCino
          standardFeature: false
          versions:
            '1.0':
              modifiedDate: '2024-12-25 16:27:45'
        0121yT1T-ramya-custom 4:
          path: dataset/0121yT1T-ramya-custom 4
          prefix: ARnCino
          standardFeature: false
          versions:
            '1.0':
              modifiedDate: '2024-12-25 16:40:49'
